version: '3'

services:
  postgres:
    image: 'postgres:11.5'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_DB=cats'
      - 'POSTGRES_PASSWORD=123'
    expose:
      - '5432'
    ports:
      - '5432:5432'
